### ISSUE TITLE
Problem compiling Jtr plugin

### ISSUE THREAD

**Issue by dummys** [donctl/sandy#8]
Hello, 

downloading jtr 1.8.0 then copying the plugin in the src folder, then ./configure and make clean && make -s, failed.

here is the trace:

~/tools/crack/jtr/john-1.8.0-jumbo-1/src$ make clean && make -s
rm -f ../run/john ../run/unshadow ../run/unafs ../run/unique ../run/undrop ../run/ssh2john ../run/rar2john ../run/zip2john ../run/genmkvpwd ../run/mkvcalcproba ../run/calc_stat ../run/tgtsnarf ../run/racf2john ../run/hccap2john ../run/pwsafe2john ../run/raw2dyna ../run/keepass2john ../run/pfx2john ../run/keychain2john ../run/keyring2john ../run/kwallet2john ../run/dmg2john ../run/putty2john ../run/uaf2john ../run/truecrypt_volume2john ../run/keystore2john ../run/wpapcap2john ../run/gpg2john ../run/cprepair ../run/luks2john ../run/base64conv
rm -f john-macosx-\* _.o escrypt/_.o _.bak core
rm -f ../run/kernels/_.cl ../run/kernels/_.h ../run/kernels/_.bin
rm -f detect bench para-bench generic.h tmp.s
rm -f cuda/_.o cuda/_~ _~
cp /dev/null Makefile.dep
make[1]: Entering directory `/home/reverser/tools/crack/jtr/john-1.8.0-jumbo-1/src/aes'
/usr/bin/find . -name \_.a -exec rm {} \;
/usr/bin/find . -name *.o -exec rm {} \;
make[1]: Leaving directory `/home/reverser/tools/crack/jtr/john-1.8.0-jumbo-1/src/aes'
make[1]: Entering directory`/home/reverser/tools/crack/jtr/john-1.8.0-jumbo-1/src/escrypt'
/bin/rm -f tests crypto_scrypt-best.o crypto_scrypt-common.o sha256.o tests.o crypto_scrypt-_.o
make[1]: Leaving directory `/home/reverser/tools/crack/jtr/john-1.8.0-jumbo-1/src/escrypt'
sandcrypt_fmt_plug.c: In function ‘set_key’:
sandcrypt_fmt_plug.c:98:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i;
      ^
sandcrypt_fmt_plug.c: In function ‘crypt_all’:
sandcrypt_fmt_plug.c:134:2: warning: pointer targets in passing argument 6 of ‘HMAC’ differ in signedness [-Wpointer-sign]
  HMAC(EVP_sha256(), key, 32, curenckey, 32, crypt_key, NULL);
  ^
In file included from sandcrypt_fmt_plug.c:23:0:
/usr/include/openssl/hmac.h:99:16: note: expected ‘unsigned char *’ but argument is of type ‘char *’
 unsigned char *HMAC(const EVP_MD *evp_md, const void *key, int key_len,
                ^
sandcrypt_fmt_plug.c:130:6: warning: variable ‘out_len’ set but not used [-Wunused-but-set-variable]
  int out_len;
      ^
sandcrypt_fmt_plug.c:129:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i;
      ^
sandcrypt_fmt_plug.c:128:16: warning: unused variable ‘fixed_hex_2’ [-Wunused-variable]
  unsigned char fixed_hex_2[17]="\x01\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f";
                ^
sandcrypt_fmt_plug.c:127:16: warning: unused variable ‘fixed_hex_1’ [-Wunused-variable]
  unsigned char fixed_hex_1[17]="\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f";
                ^
sandcrypt_fmt_plug.c: At top level:
sandcrypt_fmt_plug.c:183:2: warning: initialization makes integer from pointer without a cast [enabled by default]
  }, {
  ^
sandcrypt_fmt_plug.c:183:2: warning: (near initialization for ‘fmt_sandcrypt.params.max_keys_per_crypt’) [enabled by default]
sandcrypt_fmt_plug.c:183:2: error: initializer element is not computable at load time
sandcrypt_fmt_plug.c:183:2: error: (near initialization for ‘fmt_sandcrypt.params.max_keys_per_crypt’)
sandcrypt_fmt_plug.c:185:3: warning: initialization from incompatible pointer type [enabled by default]
   fmt_default_prepare,
   ^
sandcrypt_fmt_plug.c:185:3: warning: (near initialization for ‘fmt_sandcrypt.methods.done’) [enabled by default]
sandcrypt_fmt_plug.c:186:3: warning: initialization from incompatible pointer type [enabled by default]
   valid,
   ^
sandcrypt_fmt_plug.c:186:3: warning: (near initialization for ‘fmt_sandcrypt.methods.reset’) [enabled by default]
sandcrypt_fmt_plug.c:187:3: warning: initialization from incompatible pointer type [enabled by default]
   split,
   ^
sandcrypt_fmt_plug.c:187:3: warning: (near initialization for ‘fmt_sandcrypt.methods.prepare’) [enabled by default]
sandcrypt_fmt_plug.c:188:3: warning: initialization from incompatible pointer type [enabled by default]
   binary,
   ^
sandcrypt_fmt_plug.c:188:3: warning: (near initialization for ‘fmt_sandcrypt.methods.valid’) [enabled by default]
sandcrypt_fmt_plug.c:189:3: warning: initialization from incompatible pointer type [enabled by default]
   salt,
   ^
sandcrypt_fmt_plug.c:189:3: warning: (near initialization for ‘fmt_sandcrypt.methods.split’) [enabled by default]
sandcrypt_fmt_plug.c:190:3: warning: braces around scalar initializer [enabled by default]
   {
   ^
sandcrypt_fmt_plug.c:190:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:191:4: warning: initialization from incompatible pointer type [enabled by default]
    fmt_default_binary_hash,
    ^
sandcrypt_fmt_plug.c:191:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:192:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_binary_hash,
    ^
sandcrypt_fmt_plug.c:192:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:193:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_binary_hash,
    ^
sandcrypt_fmt_plug.c:193:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:194:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_binary_hash,
    ^
sandcrypt_fmt_plug.c:194:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:196:3: warning: excess elements in scalar initializer [enabled by default]
   },
   ^
sandcrypt_fmt_plug.c:196:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary’) [enabled by default]
sandcrypt_fmt_plug.c:197:3: warning: initialization from incompatible pointer type [enabled by default]
   fmt_default_salt_hash,
   ^
sandcrypt_fmt_plug.c:197:3: warning: (near initialization for ‘fmt_sandcrypt.methods.salt’) [enabled by default]
sandcrypt_fmt_plug.c:198:3: warning: missing braces around initializer [-Wmissing-braces]
   set_salt,
   ^
sandcrypt_fmt_plug.c:198:3: warning: (near initialization for ‘fmt_sandcrypt.methods.tunable_cost_value’) [-Wmissing-braces]
sandcrypt_fmt_plug.c:198:3: warning: initialization from incompatible pointer type [enabled by default]
sandcrypt_fmt_plug.c:198:3: warning: (near initialization for ‘fmt_sandcrypt.methods.tunable_cost_value[0]’) [enabled by default]
sandcrypt_fmt_plug.c:199:3: warning: initialization from incompatible pointer type [enabled by default]
   set_key,
   ^
sandcrypt_fmt_plug.c:199:3: warning: (near initialization for ‘fmt_sandcrypt.methods.tunable_cost_value[1]’) [enabled by default]
sandcrypt_fmt_plug.c:200:3: warning: initialization from incompatible pointer type [enabled by default]
   get_key,
   ^
sandcrypt_fmt_plug.c:200:3: warning: (near initialization for ‘fmt_sandcrypt.methods.tunable_cost_value[2]’) [enabled by default]
sandcrypt_fmt_plug.c:201:3: warning: initialization from incompatible pointer type [enabled by default]
   fmt_default_clear_keys,
   ^
sandcrypt_fmt_plug.c:201:3: warning: (near initialization for ‘fmt_sandcrypt.methods.source’) [enabled by default]
sandcrypt_fmt_plug.c:202:3: warning: initialization from incompatible pointer type [enabled by default]
   crypt_all,
   ^
sandcrypt_fmt_plug.c:202:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[0]’) [enabled by default]
sandcrypt_fmt_plug.c:203:3: warning: braces around scalar initializer [enabled by default]
   {
   ^
sandcrypt_fmt_plug.c:203:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:204:4: warning: initialization from incompatible pointer type [enabled by default]
    fmt_default_get_hash,
    ^
sandcrypt_fmt_plug.c:204:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:205:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_get_hash,
    ^
sandcrypt_fmt_plug.c:205:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:206:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_get_hash,
    ^
sandcrypt_fmt_plug.c:206:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:207:4: warning: excess elements in scalar initializer [enabled by default]
    fmt_default_get_hash,
    ^
sandcrypt_fmt_plug.c:207:4: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:209:3: warning: excess elements in scalar initializer [enabled by default]
   },
   ^
sandcrypt_fmt_plug.c:209:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[1]’) [enabled by default]
sandcrypt_fmt_plug.c:210:3: warning: initialization from incompatible pointer type [enabled by default]
   cmp_all,
   ^
sandcrypt_fmt_plug.c:210:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[2]’) [enabled by default]
sandcrypt_fmt_plug.c:211:3: warning: initialization from incompatible pointer type [enabled by default]
   cmp_one,
   ^
sandcrypt_fmt_plug.c:211:3: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[3]’) [enabled by default]
sandcrypt_fmt_plug.c:213:2: warning: initialization from incompatible pointer type [enabled by default]
  }
  ^
sandcrypt_fmt_plug.c:213:2: warning: (near initialization for ‘fmt_sandcrypt.methods.binary_hash[4]’) [enabled by default]
make[1]: *_\* [sandcrypt_fmt_plug.o] Error 1
make: **\* [default] Error 2

**Comment by devzeroo** [comment]
any updates here?
